version: '3'
services:
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    restart: always
    container_name: mongo-express
  todo-app:
    image: todo-app:1.0
    ports:
      - 3000:3000
    restart: always
    links:
      - mongodb
    container_name: todo-app
volumes:
  mongo-data:
    driver: local
